// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDygtTmRtUlyvOcfmcXx-mqV8VtWmFpaI4',
    appId: '1:286086003467:web:23273dc8c8ae46c0d5000e',
    messagingSenderId: '286086003467',
    projectId: 'rockmeet-56f83',
    authDomain: 'rockmeet-56f83.firebaseapp.com',
    databaseURL: 'https://rockmeet-56f83-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'rockmeet-56f83.firebasestorage.app',
    measurementId: 'G-RRPBE3VFQK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGqBFj5HlKzW_mrPJs8-4LaQd3g7LIA00',
    appId: '1:286086003467:android:4f77d192f2e6b132d5000e',
    messagingSenderId: '286086003467',
    projectId: 'rockmeet-56f83',
    databaseURL: 'https://rockmeet-56f83-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'rockmeet-56f83.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDygtTmRtUlyvOcfmcXx-mqV8VtWmFpaI4',
    appId: '1:286086003467:web:2ad1fcbc49713e1ad5000e',
    messagingSenderId: '286086003467',
    projectId: 'rockmeet-56f83',
    authDomain: 'rockmeet-56f83.firebaseapp.com',
    databaseURL: 'https://rockmeet-56f83-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'rockmeet-56f83.firebasestorage.app',
    measurementId: 'G-FEE30N75ZZ',
  );
}
